name: Build docker image 8.0

on:
  push:
    paths:
      - '8.0/Dockerfile'
      - '8.0/mongodump.sh'
      - 'entrypoint.sh'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-24.04]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - run: echo ${{matrix.os}}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build image
        run: docker build -t brammys/mongodump:8.0 -f ./8.0/Dockerfile .
        
      - name: Publish image
        run: docker push brammys/mongodump:8.0

      - name: Tag latest image
        run: docker tag brammys/mongodump:8.0 brammys/mongodump:latest
        
      - name: Publish latest image
        run: docker push brammys/mongodump:latest
